#!/bin/sh

#
# Run the hook command.
# Note: this will be replaced by the real command during copy.
#
GIT_USER=$(git config user.name)
GIT_EMAIL=$(git config user.email)
COMMIT_MSG_FILE=$1
DIFF_FILE='grumphp-diff'

# Fetch the GIT diff and format it as command input:
DIFF=$(git -c diff.mnemonicprefix=false --no-pager diff -r -p -m -M --full-index --no-color --staged | cat)

# Get docker-compose file path
DOCKER_COMPOSE_DIR=$(PWD)
if [[ ${DOCKER_COMPOSE_DIR} = *"/vendor/"* ]]; then
  VENDOR_PARENT_DIR=$(echo ${DOCKER_COMPOSE_DIR} | awk -F"/vendor/" '{ print $1 }')
  DOCKER_COMPOSE_DIR=${VENDOR_PARENT_DIR}/..
fi
DOCKER_COMPOSE_FILE=${DOCKER_COMPOSE_DIR}/docker-compose.yml
DOCKER_PHP_CONTAINER_ID=$(docker-compose -f ${DOCKER_COMPOSE_FILE} ps -q phpfpm)

# Remove single quotes from hook_command. It is needed to use it inside the docker exec
HOOK_COMMAND=$(echo "$(HOOK_COMMAND)" | sed "s/'//g")

# Run GrumPHP
(cd "./" && echo "${DIFF}" | \
    exec 'docker' 'run' '--rm' '-t' "--volume=$PWD:${HOOK_EXEC_PATH}" "${DOCKER_PHP_CONTAINER_ID}" \
    'vendor/bin/grumphp' 'git:pre-commit' "--git-user=$GIT_USER" "--git-email=$GIT_EMAIL" "$COMMIT_MSG_FILE" \
    '--skip-success-output')

GRUMPHP_EXIT_CODE=$?

exit $GRUMPHP_EXIT_CODE
