#!/bin/sh

#
# Run the hook command.
# Note: this will be replaced by the real command during copy.
#

# Fetch the GIT diff and format it as command input:
DIFF=$(git -c diff.mnemonicprefix=false --no-pager diff -r -p -m -M --full-index --no-color --staged | cat)

# Get docker-compose file path
DOCKER_COMPOSE_DIR=$(PWD)
if [[ ${DOCKER_COMPOSE_DIR} = *"/vendor/"* ]]; then
  VENDOR_PARENT_DIR=$(echo ${DOCKER_COMPOSE_DIR} | awk -F"/vendor/" '{ print $1 }')
  DOCKER_COMPOSE_DIR=${VENDOR_PARENT_DIR}/..
fi
DOCKER_COMPOSE_FILE=${DOCKER_COMPOSE_DIR}/docker-compose.yml
DOCKER_PHP_CONTAINER_ID=$(docker-compose -f ${DOCKER_COMPOSE_FILE} ps -q phpfpm)

# Run GrumPHP
(cd "${HOOK_EXEC_PATH}" && printf "%s\n" "${DIFF}" | docker exec -t ${DOCKER_PHP_CONTAINER_ID} $(HOOK_COMMAND) '--skip-success-output')